stages:
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

build-windows:
  stage: build
  tags:
    - windows
  before_script:
    - choco install nodejs -y
    - npm install -g npm@latest
    - $env:PATH = "C:\Program Files\nodejs;$env:PATH"
    - rustup target add x86_64-pc-windows-msvc
  script:
    - npm install
    - npm run build
    - npm run tauri build
  artifacts:
    paths:
      - src-tauri/target/release/bundle/msi/*.msi
      - src-tauri/target/release/bundle/nsis/*.exe
    expire_in: 2 week
  only:
    - develop
    - main
    - offline

build-macos:
  stage: build
  tags:
    - macos
  before_script:
    - npm install
  script:
    - npm run build
    - npm run tauri build
  artifacts:
    paths:
      - src-tauri/target/release/bundle/dmg/*.dmg
      - src-tauri/target/release/bundle/macos/*.app
    expire_in: 1 week
  only:
    - develop
    - main
    - offline
